name: Attach Doc to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # 3. Génération du .adoc à partir de l'Excel
      - name: Generate AsciiDoc
        run: python generate_doc.py

      # 4. Setup Ruby & Asciidoctor
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Asciidoctor
        run: gem install asciidoctor

      # 5. Conversion en HTML (Utilisation du style par défaut "Book")
      - name: Build HTML
        run: asciidoctor output.adoc -o index.html

      # 6. Upload du fichier dans la Release
      - name: Upload HTML to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}